title: M³
title-abbreviated: M³
description: Description
url: ""
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
is_government: true
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
    - travis-script.js
    - .travis.yml
    - README.md
    - package.json
    - package-lock.json
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - Gemfile
    - Gemfile.lock
collections:
    who-we-are:
        output: true
    focus-areas:
        output: true
    m3-towns:
        output: true
    useful-links:
        output: true
    inspirasisg:
        output: true
    sgteguhbersatu:
        output: true
    ciptasamam3:
        output: true
resources_name: media-centre
no_contact: false
favicon: /images/favicon-m3.ico
google_analytics: UA-141688776-1
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
